services:
  timbr-db:
    image: timbr.azurecr.io/timbr-mysql-8:latest
    container_name: timbr-db
    environment:
      - MYSQL_ROOT_PASSWORD=db_pass
    restart: always
    networks:
      - timbr-net
    volumes:
      - db-volume:/var/lib/mysql/
  timbr-server:
    image: timbr.azurecr.io/timbr-server-stable:latest
    container_name: timbr-server
    environment:
      - TIMBR_DB_JDBC=jdbc:mysql://timbr-db:3306
      - TIMBR_DB_JDBC_DRIVER=com.mysql.jdbc.Driver
      - TIMBR_DB_USER=db_user
      - TIMBR_DB_PASSWORD=db_pass
      - TIMBR_DB_JDBC_PARAMS=useSSL=false&amp;allowPublicKeyRetrieval=true
      - TIMBR_CONNECTION_WORKER_THREADS=100
      - TIMBR_OPERATION_WORKER_THREADS=100
      - TIMBR_INIT_MEMORY=-Xms256m
      - TIMBR_MAX_MEMORY=-Xmx4096m
    restart: always
    networks:
      - timbr-net
    ports:
      - "11000:11000"
    depends_on:
      - timbr-db
  timbr-platform:
    image: timbr.azurecr.io/timbr-platform-stable:latest
    container_name: timbr-platform
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=timbr-mysql
      - DB_PORT=3306
      - DB_DATABASE=timbr_platform
      - DB_USERNAME=db_user
      - DB_PASSWORD=db_pass
      - SQLLAB_LIMIT=1000
      - FLASK_ENV=production
      - THRIFT_HOST=timbr-server
      - ENFORCE_SSL=1
    networks:
      - timbr-net
    restart: always
    ports:
      - "8088:8088"
    depends_on:
      - timbr-db

networks:
  timbr-net:
    driver: bridge

volumes:
  db-volume: