services:
  timbr-ga:
    image: timbr.azurecr.io/timbr-ga:latest
    container_name: timbr-ga
    environment:
      - TIMBR_DB_JDBC=jdbc:mysql://timbr-db:3306
      - TIMBR_DB_JDBC_DRIVER=com.mysql.jdbc.Driver
      - TIMBR_DB_USER=db_user
      - TIMBR_DB_PASSWORD=db_pass
      - THRIFT_HOST=timbr-server
    networks:
      - timbr-net
    depends_on:
      - timbr-db