events {
  worker_connections 1024;
}

http {
  proxy_read_timeout 1200s;
  proxy_connect_timeout 1200s;
  proxy_send_timeout 1200s;
  resolver 127.0.0.11 ipv6=off;
  
  server {
    listen 80 default_server;
    server_name _;
    return 301 https://$host$request_uri;
  }
  
  server {
    listen 443 ssl;
    port_in_redirect off;
    ssl_certificate     /usr/lib/ssl/domain_cert.pem;
    ssl_certificate_key /usr/lib/ssl/private_key.pem;
    
    location / {
      set $upstream_proxy http://timbr-platform:8088;
      proxy_pass $upstream_proxy$request_uri;
      proxy_set_header Host $host;
      proxy_set_header User-Agent: $http_user_agent;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
    location /timbr-server {
      set $upstream_proxy http://timbr-server:11000;
      proxy_pass $upstream_proxy$request_uri;
      proxy_set_header Host $host;
      proxy_set_header User-Agent: $http_user_agent;
    }
    location /hive2 {
      set $upstream_proxy http://timbr-server:11000;
      proxy_pass $upstream_proxy$request_uri;
      proxy_set_header Host $host;
      proxy_set_header User-Agent: $http_user_agent;
    }
    location /cliservice {
      set $upstream_proxy http://timbr-server:11000;
      proxy_pass $upstream_proxy$request_uri;
      proxy_set_header Host $host;
      proxy_set_header User-Agent: $http_user_agent;
    }
    
    # Optional routing for additional services
    location /mdx {
      set $upstream_proxy http://timbr-mdx:12000;
      proxy_pass $upstream_proxy$request_uri;
      proxy_set_header Host $host;
      proxy_set_header User-Agent: $http_user_agent;
    }
    location /timbr/openapi {
      set $upstream_proxy http://timbr-api:9000;
      proxy_pass $upstream_proxy$request_uri;
      proxy_set_header Host $host;
      proxy_set_header User-Agent: $http_user_agent;
    }
    location /timbr/api {
      set $upstream_proxy http://timbr-api:9000;
      proxy_pass $upstream_proxy$request_uri;
      proxy_set_header Host $host;
      proxy_set_header User-Agent: $http_user_agent;
    }
  }
}