{{- if .Values.components.server.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.components.server.name }}
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
  labels:
{{ include "timbr.labels" . | indent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.components.server.service.type }}
  ports:
    - name: thrift
      port: {{ .Values.components.server.service.port }}
      targetPort: 11000
      protocol: TCP
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.components.server.name }}
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
  labels:
{{ include "timbr.labels" . | indent 4 }}
    app.kubernetes.io/component: server
spec:
  replicas: {{ .Values.components.server.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: server
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
{{ include "timbr.labels" . | indent 8 }}
        app.kubernetes.io/component: server
    spec:
{{ include "timbr.imagePullSecrets" . | indent 6 }}
      containers:
        - name: timbr
          image: {{ .Values.components.server.image | quote }}
          imagePullPolicy: Always
          ports:
            - containerPort: 11000
              name: thrift
          env:
            - name: TIMBR_DB_JDBC
              value: {{ printf "jdbc:mysql://%s:%v" .Values.db.host .Values.db.port | quote }}
            - name: TIMBR_DB_USER
              value: {{ .Values.db.user | quote }}
            - name: TIMBR_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "timbr.secretName" . }}
                  key: {{ .Values.db.rootPasswordSecretKey | quote }}
            {{- range $k, $v := .Values.components.server.env }}
            {{- if and (ne $k "extra") (ne $v nil) }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
            {{- end }}
            {{- with .Values.components.server.env.extra }}
            {{- range $k, $v := . }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
            {{- end }}
{{- end }}
